<a href="https://colab.research.google.com/github/neerajguleria1/driver-drowsiness-detection/blob/main/Day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# Numpy Operations
import numpy as np
speeds=np.array([120,250,110,230,270,160])
print(speeds)
print("type:", type(speeds))
print("shape",speeds.shape)
print("data type:", speeds.dtype)

print("Max:",np.max(speeds))
print("min",np.min(speeds))
print("average:",np.mean(speeds))
print("Total:",np.sum(speeds))
print("standard deviation",np.std(speeds))

speed_Limit=200;
overspeeding=speeds>speed_Limit
print("overspeeding",overspeeding)

#Now we adjust speed
#it automatically reduce speed by 10%
adjusted_speed=np.where(overspeeding,speeds*0.9,speeds)
print("Adjusted speed",adjusted_speed)

# 2D Arrays
driver_speed=np.array([
    [150,290,333],
    [222,69,77],
    [221,697,89]
])
print("shape",driver_speed.shape)
print("average speed pre driver:",np.mean(driver_speed,axis=1))#acrooss colums
print("average speed per trip:",np.mean(driver_speed,axis=0))


[120 250 110 230 270 160]
type: <class 'numpy.ndarray'>
shape (6,)
data type: int64
Max: 270
min 110
average: 190.0
Total: 1140
standard deviation 62.98147875897061
overspeeding [False  True False  True  True False]
Adjusted speed [120. 225. 110. 207. 243. 160.]
shape (3, 3)
average speed pre driver: [257.66666667 122.66666667 335.66666667]
average speed per trip: [197.66666667 352.         166.33333333]


In [33]:
import numpy as np
driver_speeds=np.array([
    [120,102,185],
    [220,198,182],
    [170,198,148],
    [160,128,198]
])
fastest_speed=np.max(driver_speeds)
print(fastest_speed)
speed_limit=180
overspeeding=driver_speeds > speed_limit
adjusted_speeds=np.where(overspeeding,driver_speeds*0.9,driver_speeds)
print(overspeeding)
print(adjusted_speeds)

220
[[False False  True]
 [ True  True  True]
 [False  True False]
 [False False  True]]
[[120.  102.  166.5]
 [198.  178.2 163.8]
 [170.  178.2 148. ]
 [160.  128.  178.2]]
