<a href="https://colab.research.google.com/github/neerajguleria1/driver-drowsiness-detection/blob/main/Day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Basics
Understand how to handle large numeric data using NumPy arrays.
Learn why NumPy is faster than lists and how to use it in Google Colab.


In [12]:
# Install & Import Numpy
import numpy as np

a=np.array([2,5,7,3])
b=np.array([[2,5,7,2],[2,56,73,1]])

print(a)
print(b)

print("Shape:",b.shape)
print("Dimension",b.ndim)
print("Data type:",b.dtype)
print("Size",b.size)

[2 5 7 3]
[[ 2  5  7  2]
 [ 2 56 73  1]]
Shape: (2, 4)
Dimension 2
Data type: int64
Size 8


In [27]:
# Special Arrays
print("Zeroes",np.zeros((3,3)))
print("Ones",np.ones((2,4)))
print("Range:",np.arange(0,10,2))
print("Random:",np.random.randint(1,100,size=(4,3)))


Zeroes [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range: [0 2 4 6 8]
Random: [[40 44 35]
 [91 80 85]
 [92 66  6]
 [24 97 70]]


In [34]:
# Array Indexing and Slicing
arr=np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[1:4])

# 2D array
arr2d=np.array([[1,2,4,7],[3,3,5,6]])
print("Row 0",arr2d[0])
print("Element (1,2)",arr2d[1,2])

1
[2 3 4]
Row 0 [1 2 4 7]
Element (1,2) 5


In [40]:
# Mathematical Operations
x=np.array([1,2,4])
y=np.array([2,5,6])
print("addition",x+y)
print(x*y)
print(x**y)
print("Mean",np.mean(y))
print("Max",np.max(y))

addition [ 3  7 10]
[ 2 10 24]
[   1   32 4096]
Mean 4.333333333333333
Max 6


In [47]:
# Real Life Example
speeds=np.array([110,150,440,230,57,88,189,288])
print("Average speed",np.mean(speeds))
print("Top speed",np.max(speeds))
print("Driver above 200:",sum(speeds>200))

Average speed 194.0
Top speed 440
Driver above 200: 3
