<a href="https://colab.research.google.com/github/neerajguleria1/driver-drowsiness-detection/blob/main/Day13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Statistical Opeartions
import  numpy as np

driver_speeds = np.array([
    [120, 102, 185],
    [220, 198, 182],
    [170, 198, 148],
    [160, 128, 198]
])

mean_speed = np.mean(driver_speeds)
median_speed = np.median(driver_speeds)
std_speed = np.std(driver_speeds)
var_speed = np.var(driver_speeds)

print("Mean speed:", mean_speed)
print("Median speed:", median_speed)
print("Standard Deviation:", std_speed)
print("Variance:", var_speed)

# Mean speed per driver
mean_per_driver = np.mean(driver_speeds, axis=1)
print("Mean speed per driver:", mean_per_driver)

# Mean speed per trip
mean_per_trip = np.mean(driver_speeds, axis=0)
print("Mean speed per trip:", mean_per_trip)

overall_avg=np.mean(driver_speeds)
driver_avg=np.mean(driver_speeds,axis=1)
closest_driver=np.argmin(np.abs(driver_avg-overall_avg))
print(closest_driver)

Mean speed: 167.41666666666666
Median speed: 176.0
Standard Deviation: 34.89617537145805
Variance: 1217.7430555555554
Mean speed per driver: [135.66666667 200.         172.         162.        ]
Mean speed per trip: [167.5  156.5  178.25]
2


In [15]:
# Tasks
'''Create a new array with 5 drivers and 4 trips.

Calculate for each driver:

Mean

Max

Min

Standard deviation

Print the driver with most consistent speeds (lowest std deviation).'''

import numpy as np
driver_speeds = np.array([
    [120, 102, 185,336],
    [220, 198, 182,55],
    [170, 198, 148,88],
    [160, 128, 198,129],
    [260, 188, 158,129]
])
each_driver_mean=np.mean(driver_speeds,axis=1)
print(each_driver_mean)

each_driver_max=np.max(driver_speeds,axis=1)
print(each_driver_max)

each_driver_min=np.min(driver_speeds,axis=1)
print(each_driver_min)

each_driver_stdDev=np.std(driver_speeds,axis=1)
print(each_driver_stdDev)

lowest_std_dev=np.min(each_driver_stdDev)
print(lowest_std_dev)

most_consistent_driver_index=np.argmin(each_driver_stdDev)
most_consistent_driver_std=each_driver_stdDev[most_consistent_driver_index]

print(f"\nDriver {most_consistent_driver_index+1} is most consistent driver" f"(std deviations is: {most_consistent_driver_std:2f})")



[185.75 163.75 151.   153.75 183.75]
[336 220 198 198 260]
[102  55  88 128 129]
[92.07707369 64.21983728 40.45985665 28.603977   48.71537232]
28.603976996215053

Driver 4 is most consistent driver(std deviations is: 28.603977)
